import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// huddle01
import HuddleWrapper from "@/wrappers/HuddleWrapper";
import { getAccessToken } from "@/utils/getAccessToken";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const accessToken = await getAccessToken("xtm-xxbk-ikg");

  // console.log("accessToken", accessToken);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div>{accessToken}</div> */}
        <HuddleWrapper>{children}</HuddleWrapper>
      </body>
    </html>
  );
}
